name: Nix Cache Build

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Push to Cachix
      uses: cachix/cachix-action@v12
      with:
        name: pcortellezzi
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build Nix packages
      run: nix build .#
        
