name: Update atas-x-wine package
on:
  repository_dispatch:
    types: [update-atas-x-wine]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Run update script
        run: nix flake update atas-x-wine
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git diff --quiet flake.lock; then
            git add flake.lock
            git commit -m "atas-x-wine: auto-update flake input"
            git push
          else
            echo "atas-x-wine is already up to date."
          fi
